/**
 * Simple commands that should be handled WITHOUT the LLM (from the V2 spec).
 * Used for the before/after coverage benchmark.
 */
export const SIMPLE_COMMANDS: Record<string, string[]> = {
  shopping: [
    "Ajoute du lait aux courses",
    "Ajoute lait courses",
    "Mets du lait dans la liste",
    "Mets du lait sur la liste",
    "Rajoute du lait",
    "Rajoute du lait dans mes courses",
    "Note du lait pour les courses",
    "Il faut du lait",
    "Il nous faut du lait",
    "Pense à acheter du lait",
    "Pense à prendre du lait",
    "Mets-moi du lait dans les courses",
    "Ajoute-moi du lait à la liste",
    "Rajoute du pain",
    "Mets des œufs dans la liste",
    "Note des tomates",
    "Il nous faut du beurre",
    "Il me faut du café",
    "Pense à acheter du PQ",
    "Ajoute 6 œufs",
    "Mets 2 bouteilles de lait",
    "Rajoute un kilo de pommes",
    "Prends aussi du fromage",
    "Ajoute lait, pain, œufs et tomates",
    "Enlève le lait",
    "Retire les tomates",
    "Supprime le pain des courses",
    "Finalement pas besoin de café",
    "J'ai pris le lait",
    "Coche les œufs",
    "Le pain c'est bon",
    "J'ai acheté les tomates",
    "Marque le lait comme acheté",
    "Qu'est-ce qu'il reste aux courses ?",
    "Il reste quoi ?",
    "Lis-moi la liste",
    "Qu'est-ce qu'on doit acheter ?",
    "Montre les courses",
    "euh ajoute moi du lait dans les courses s'il te plaît",
  ],
  timers: [
    "Minuteur 8 minutes",
    "Lance un minuteur de 8 minutes",
    "8 minutes pour les pâtes",
    "Mets 10 minutes pour le four",
    "Chrono 5 minutes",
    "Rappelle-moi dans 20 minutes de sortir le linge",
    "Ajoute 2 minutes au minuteur",
    "Pause le minuteur",
    "Reprends le minuteur",
    "Annule le minuteur des pâtes",
    "Combien de temps reste-t-il ?",
    "Minuteur 1h20",
    "Minuteur une heure et demie",
  ],
  music: [
    "Mets de la musique",
    "Lance Spotify",
    "Pause",
    "Pause la musique",
    "Reprends",
    "Suivante",
    "Passe à la suivante",
    "Précédente",
    "Mets le son à 30 %",
    "Monte le son",
    "Baisse le son",
    "Mets ma playlist cuisine",
    "Lance Chill",
    "Mets Daft Punk",
    "Mets Instant Crush",
    "Qu'est-ce qui joue ?",
    "C'est quoi cette musique ?",
    "Mets Spotify sur le salon",
  ],
  scenes: [
    "Mode cuisine",
    "Passe en cuisine",
    "Active la scène cuisine",
    "Mets le mode matin",
    "Mode soir",
    "Passe en mode soirée",
    "Quitte le mode cuisine",
    "Reviens au mode normal",
  ],
  navigation: [
    "Ouvre Waze",
    "Lance l'itinéraire",
    "Emmène-moi au prochain rendez-vous",
    "Quand dois-je partir ?",
    "À quelle heure je pars ?",
    "Combien de temps pour y aller ?",
    "Lance Google Maps",
    "Ouvre Plans",
    "Quand dois-je partir pour mon prochain rendez-vous ?",
  ],
  weather: [
    "Quel temps fait-il ?",
    "Il va pleuvoir ?",
    "Météo demain",
    "Quel temps samedi ?",
    "Il fera combien à Annecy ?",
    "Est-ce qu'il pleuvra pour mon rendez-vous ?",
  ],
  calendar: [
    "Ajoute dentiste jeudi à 16h",
    "Mets CrossFit demain à 18h30",
    "Restaurant vendredi 20h",
    "Ajoute réunion lundi de 9h à 10h",
    "Note congé vendredi toute la journée",
    "J'ai quoi aujourd'hui ?",
    "Qu'est-ce que j'ai demain ?",
    "C'est quoi mon prochain rendez-vous ?",
    "Que fait-on samedi ?",
    "Décale le dentiste à 17h",
    "Mets le CrossFit à 19h",
    "Déplace la réunion à demain",
  ],
  reminders: [
    "Rappelle-moi d'appeler maman à 18h",
    "Rappelle-moi demain à 9h de prendre le dossier",
    "Annule mon rappel",
  ],
};
