/**
 * "Real life" spoken phrasing — harder than the baseline corpus (oral French, STT noise,
 * conversational turns). Everything in EVERYDAY_COMMANDS should be handled WITHOUT the LLM.
 *
 * Phrases can be annotated with the expected router intent: `["phrase", "intent"]`.
 * A prefix ending with "." matches a whole domain ("calendar." accepts calendar.today…).
 * The coverage bench reports both LLM fallbacks AND wrong intents.
 *
 * Fixture context: Wednesday 7 Oct 2026, 18:00 — Dentiste Thu 16h, CrossFit today 18:30,
 * Réunion Fri 9h. Profiles Clément / Compagne.
 */
export type CorpusEntry = string | [phrase: string, intent: string];

export const EVERYDAY_COMMANDS: Record<string, CorpusEntry[]> = {
  conversation: [
    "Répète",
    "Répète s'il te plaît",
    "Tu peux répéter ?",
    "Peux-tu répéter",
    "Je n'ai pas entendu",
    "J'ai pas entendu",
    "J'ai pas compris",
    "Je n'ai pas compris ce que tu as dit",
    "Quoi ?",
    "Pardon ?",
    "Comment ?",
    "Hein ?",
    "Redis-moi ça",
    "Redis",
    "Tu as dit quoi ?",
    "Qu'est-ce que tu as dit ?",
    "Encore une fois",
    "Plus lentement",
    "Merci",
    "Merci beaucoup",
    "Super merci",
    "C'est gentil",
    "Parfait",
    "Ok",
    "D'accord",
    "Bonjour",
    "Salut",
    "Bonsoir",
    "Bonne nuit",
    "Ça va ?",
    "Comment tu vas ?",
    "Qui es-tu ?",
    "Comment tu t'appelles ?",
    "Qu'est-ce que tu sais faire ?",
    "Aide",
    "Aide-moi",
    "Laisse tomber",
    "Annule",
    "Non rien",
    "C'est bon",
    "Stop",
    "Tais-toi",
    "Chut",
    "Oublie",
    "Quelle heure est-il ?",
    "Il est quelle heure ?",
    "On est quel jour ?",
    "Quel jour on est ?",
    "C'est quoi la date ?",
    "On est le combien ?",
    ["Annule ce que tu viens de faire", "conversation.undo"],
    ["Annule la dernière action", "conversation.undo"],
  ],

  "shopping+": [
    ["Faut racheter du lait", "shopping.add"],
    ["On n'a plus de lait", "shopping.add"],
    ["Y a plus de beurre", "shopping.add"],
    ["Il n'y a plus de café", "shopping.add"],
    ["On est à court de PQ", "shopping.add"],
    ["Ajoute du dentifrice sur la liste de courses", "shopping.add"],
    ["Mets du liquide vaisselle", "shopping.add"],
    ["Rajoute deux paquets de pâtes", "shopping.add"],
    ["Ajoute des bananes et du yaourt", "shopping.add"],
    ["N'oublie pas le pain", "shopping.add"],
    ["Ajoute de la lessive aux courses", "shopping.add"],
    ["Note qu'il faut des piles", "shopping.add"],
    ["Ajoute à la liste des courses du jambon", "shopping.add"],
    ["Courses : lait, œufs, farine", "shopping.add"],
    ["J'ai besoin de sel", "shopping.add"],
    ["Enlève les bananes de la liste", "shopping.remove"],
    ["Supprime le jambon des courses", "shopping.remove"],
    ["Plus besoin de pain", "shopping.remove"],
    ["C'est bon pour le lait", "shopping.complete"],
    ["J'ai trouvé le beurre", "shopping.complete"],
    ["Le café c'est pris", "shopping.complete"],
    ["Coche le dentifrice", "shopping.complete"],
    ["Qu'est-ce qu'il y a sur la liste ?", "shopping.list"],
    ["Dis-moi ce qu'il faut acheter", "shopping.list"],
    ["C'est quoi la liste de courses ?", "shopping.list"],
    ["Il manque quoi ?", "shopping.list"],
    ["On a besoin de quoi ?", "shopping.list"],
    ["Liste de courses", "shopping.list"],
    ["Efface ce qui est coché", "shopping.clearCompleted"],
    ["Vide les articles achetés", "shopping.clearCompleted"],
  ],

  "timers+": [
    ["Mets un minuteur de 3 minutes", "timer.create"],
    ["Minuteur dix minutes", "timer.create"],
    ["Un minuteur de vingt minutes pour le gâteau", "timer.create"],
    ["Préviens-moi dans 15 minutes", "timer.create"],
    ["Sonne dans 5 minutes", "timer.create"],
    ["Compte 7 minutes", "timer.create"],
    ["Timer 12 minutes", "timer.create"],
    ["Minuteur 30 secondes", "timer.create"],
    ["Minuteur d'une demi-heure", "timer.create"],
    ["Minuteur un quart d'heure", "timer.create"],
    ["Lance le minuteur des œufs 9 minutes", "timer.create"],
    ["Il reste combien de temps ?", "timer.remaining"],
    ["Combien de temps reste-t-il sur le minuteur ?", "timer.remaining"],
    ["Où en est le minuteur ?", "timer.remaining"],
    ["Arrête le minuteur", "timer.cancel"],
    ["Stop minuteur", "timer.cancel"],
    ["Supprime le minuteur", "timer.cancel"],
    ["Coupe le minuteur", "timer.cancel"],
    ["Mets le minuteur en pause", "timer.pause"],
    ["Relance le minuteur", "timer.resume"],
    ["Rajoute 5 minutes", "timer.extend"],
    ["Encore 3 minutes", "timer.extend"],
    ["Quels minuteurs sont en cours ?", "timer.list"],
    ["J'ai combien de minuteurs ?", "timer.list"],
  ],

  "music+": [
    ["Mets de la musique s'il te plaît", "music."],
    ["Lance la musique", "music.resume"],
    ["Joue de la musique", "music."],
    ["Mets un peu de musique", "music."],
    ["Arrête la musique", "music.pause"],
    ["Coupe le son", "music."],
    ["Coupe la musique", "music.pause"],
    ["Remets la musique", "music.resume"],
    ["Chanson suivante", "music.next"],
    ["Morceau suivant", "music.next"],
    ["Change de chanson", "music.next"],
    ["Zappe", "music.next"],
    ["Skip", "music.next"],
    ["Reviens à la chanson d'avant", "music.previous"],
    ["La précédente", "music.previous"],
    ["Plus fort", "music.volume"],
    ["Moins fort", "music.volume"],
    ["Monte un peu", "music.volume"],
    ["Baisse un peu le son", "music.volume"],
    ["Volume à 50", "music.volume"],
    ["Mets le volume à fond", "music.volume"],
    ["C'est quoi ce morceau ?", "music.current"],
    ["C'est qui qui chante ?", "music.current"],
    ["Quelle est cette chanson ?", "music.current"],
    ["Mets du Daft Punk", "music.play"],
    ["Joue Instant Crush", "music.play"],
    ["Lance ma playlist Chill", "music.playlist"],
    ["Mets la playlist du matin", "music.playlist"],
    ["Mets la musique sur l'iPhone", "music.device"],
  ],

  "scenes+": [
    ["On passe en mode cuisine", "scene.activate"],
    ["Mode matin", "scene.activate"],
    ["Active le mode soirée", "scene.activate"],
    ["Lance le mode soir", "scene.activate"],
    ["Sors du mode cuisine", "scene.exit"],
    ["Désactive le mode", "scene.exit"],
    ["Mode normal", "scene.exit"],
    ["Quels sont les modes ?", "scene.list"],
  ],

  "navigation+": [
    ["Je dois partir quand ?", "navigation.nextDeparture"],
    ["Il faut que je parte à quelle heure ?", "navigation.nextDeparture"],
    ["Je pars quand pour le CrossFit ?", "navigation."],
    ["Combien de temps pour aller au CrossFit ?", "navigation.travelTime"],
    ["Combien de temps jusqu'à la gare ?", "navigation.travelTime"],
    ["Il faut combien de temps pour aller chez les parents ?", "navigation.travelTime"],
    ["Emmène-moi à la gare", "navigation.open"],
    ["Itinéraire vers le CrossFit", "navigation.open"],
    ["Guide-moi jusqu'à la maison", "navigation.open"],
    ["Ramène-moi à la maison", "navigation.open"],
    ["Ouvre le GPS", "navigation.open"],
  ],

  "weather+": [
    ["Il fait combien dehors ?", "weather."],
    ["Il fait quel temps ?", "weather."],
    ["Il fait beau ?", "weather."],
    ["Il fait froid ?", "weather."],
    ["Quelle température fait-il ?", "weather."],
    ["Il pleut ?", "weather."],
    ["Est-ce qu'il va pleuvoir demain ?", "weather.date"],
    ["Faut-il prendre un parapluie ?", "weather."],
    ["Je prends un parapluie ?", "weather."],
    ["La météo pour ce week-end", "weather."],
    ["Quel temps fera-t-il dimanche ?", "weather.date"],
    ["Météo à Genève", "weather.location"],
    ["Il va faire beau demain ?", "weather.date"],
  ],

  "calendar+": [
    ["Qu'est-ce qu'on a ce soir ?", "calendar.today"],
    ["J'ai un truc demain ?", "calendar.tomorrow"],
    ["Est-ce que j'ai quelque chose demain ?", "calendar.tomorrow"],
    ["On fait quoi ce week-end ?", "calendar.range"],
    ["Mon agenda de demain", "calendar.tomorrow"],
    ["C'est quoi le programme demain ?", "calendar.tomorrow"],
    ["Qu'est-ce que j'ai cette semaine ?", "calendar.range"],
    ["J'ai quoi vendredi ?", "calendar.day"],
    ["C'est quand le dentiste ?", "calendar.search"],
    ["Le dentiste c'est quand ?", "calendar.search"],
    ["À quelle heure j'ai la réunion ?", "calendar.search"],
    ["Mon prochain rendez-vous ?", "calendar.next"],
    ["C'est quoi la suite ?", "calendar.next"],
    ["Ajoute coiffeur samedi à 10h", "calendar.create"],
    ["Rendez-vous chez le médecin lundi à 14h30", "calendar.create"],
    ["Mets un rendez-vous avec le garagiste mardi 8h", "calendar.create"],
    ["Rajoute anniversaire de Paul le 12 novembre à 19h", "calendar.create"],
    ["Bloque jeudi après-midi pour le déménagement", "calendar.create"],
    ["Supprime le dentiste", "calendar.delete"],
    ["Annule la réunion de vendredi", "calendar.delete"],
    ["Repousse le dentiste d'une heure", "calendar.move"],
    ["Avance la réunion de 30 minutes", "calendar.move"],
    ["Décale le CrossFit à demain", "calendar.move"],
    ["Est-ce qu'on est libres samedi ?", "calendar.availability"],
    ["Je suis dispo quand demain ?", "calendar.availability"],
  ],

  "reminders+": [
    ["Rappelle-moi de sortir les poubelles ce soir à 21h", "reminder.create"],
    ["Rappelle-moi d'appeler le plombier demain", "reminder.create"],
    ["Fais-moi penser à arroser les plantes à 19h", "reminder.create"],
    ["N'oublie pas de me rappeler de payer la facture vendredi", "reminder.create"],
    ["Mets-moi un rappel pour le vétérinaire jeudi à 10h", "reminder.create"],
    ["Quels sont mes rappels ?", "reminder.list"],
    ["J'ai des rappels ?", "reminder.list"],
    ["Supprime le rappel du plombier", "reminder.cancel"],
  ],
};

/**
 * Blind round: written AFTER the parser fixes, without touching the code, to measure how well
 * the router generalises (not merged into EVERYDAY_COMMANDS until reviewed).
 */
export const BLIND_COMMANDS: Record<string, CorpusEntry[]> = {
  blind: [
    ["Tu peux me redire ça ?", "conversation.repeat"],
    ["J'ai rien compris", "conversation.repeat"],
    ["Excuse-moi, tu peux répéter ?", "conversation.repeat"],
    ["Il est quelle heure là ?", "conversation.time"],
    ["Merci HomeCal", "conversation.thanks"],
    ["Ajoute des tomates cerises", "shopping.add"],
    ["Faut du shampoing", "shopping.add"],
    ["On n'a plus d'œufs", "shopping.add"],
    ["Mets des croquettes pour le chat sur la liste", "shopping.add"],
    ["Retire le dentifrice", "shopping.remove"],
    ["J'ai pris le shampoing", "shopping.complete"],
    ["Qu'est-ce qu'il faut prendre au magasin ?", "shopping.list"],
    ["Minuteur 4 minutes pour le thé", "timer.create"],
    ["Mets un minuteur d'une heure", "timer.create"],
    ["Préviens-moi dans une demi-heure", "timer.create"],
    ["Annule tous les minuteurs", "timer.cancel"],
    ["Combien de temps il reste au minuteur des pâtes ?", "timer.remaining"],
    ["Mets du jazz", "music.play"],
    ["Mets la radio", "music."],
    ["Passe à la chanson suivante", "music.next"],
    ["Baisse le volume", "music.volume"],
    ["Mets le son à 20", "music.volume"],
    ["Remets la chanson d'avant", "music.previous"],
    ["Arrête Spotify", "music.pause"],
    ["Active le mode cuisine", "scene.activate"],
    ["Sortir du mode soirée", "scene.exit"],
    ["Combien de temps pour aller à la gare à pied ?", "navigation.travelTime"],
    ["À quelle heure je dois partir pour le dentiste ?", "navigation.nextDeparture"],
    ["Lance Waze vers le CrossFit", "navigation.open"],
    ["Il va faire chaud demain ?", "weather.date"],
    ["Il pleuvra samedi ?", "weather.date"],
    ["Quel temps à Lausanne ?", "weather."],
    ["Qu'est-ce qu'on a demain soir ?", "calendar.tomorrow"],
    ["J'ai quoi lundi ?", "calendar.day"],
    ["Quand est la réunion ?", "calendar.search"],
    ["Ajoute piscine dimanche à 10h", "calendar.create"],
    ["Dîner chez les parents samedi à 19h", "calendar.create"],
    ["Supprime la réunion", "calendar.delete"],
    ["Décale la réunion à 11h", "calendar.move"],
    ["Est-ce que je suis libre jeudi matin ?", "calendar.availability"],
    ["Rappelle-moi de prendre mes médicaments à 20h", "reminder.create"],
    // short delay "rappelle-moi dans X de Y" = labelled timer (same design as the baseline corpus)
    ["Rappelle-moi dans une heure d'appeler Paul", "timer.create"],
    ["Annule le rappel", "reminder.cancel"],
  ],
};

/** Genuinely complex requests: the router must NOT execute them, they belong to the LLM. */
export const LLM_EXPECTED: string[] = [
  "Organise ma journée de samedi pour que je puisse faire du sport et voir mes parents",
  "Trouve un créneau où on est libres tous les deux pour un restaurant la semaine prochaine, plutôt le soir mais pas le mardi",
  "Déplace tous mes rendez-vous de jeudi à vendredi sauf le dentiste",
  "Qu'est-ce que je pourrais cuisiner avec ce qu'il y a sur la liste de courses ?",
  "Explique-moi pourquoi le ciel est bleu",
  "Écris un message d'anniversaire pour ma mère",
  "Si il pleut samedi, décale le footing à dimanche, sinon garde-le",
  "Combien de rendez-vous j'ai eu ce mois-ci comparé au mois dernier ?",
];
